### PR TITLE
Ignore keyframes, update deps

### PR DESCRIPTION
**Pull request by komachi**

### CODE REVIEW

**Comment by AoDev** [comment]
Hello! Thank you for the update!  (I thought nobody used this module to be honest)

I'd like to know what is the problem with the keyframes? Were they wongly deleted?
If they match the patterns, they should be deleted too, don't you think?

**Comment by komachi** [comment]
I tried to use regexp `/^[A-Za-z\[\*]/` for removing global selectors and ran into this issue. It empties keyframes anyway, not deletes them completely, because `rule.selectors` for keyframes contains keyframe selectors.

**Comment by AoDev** [comment]
@komachi Sorry for not coming back at you. I wanted to ask you if what done here: https://github.com/AoDev/css-byebye/pull/10  helps with the problem you had?

**Comment by AoDev** [comment]
I am closing this PR as there were no activity for one year.

**Pull request closed without merging**
